### ISSUE TITLE
헤더 로그인 상태 반영 에러

### ISSUE THREAD

**Issue by ktmihs** [thenolja/desktop#113]
## 설명
아래 사진과 같이 로그인이 된 상태임에도 헤더에 반영이 되지 않습니다.
![image](https://user-images.githubusercontent.com/63227474/159832590-9bd6583d-144c-4b84-a707-00d7417713cd.png)

## 구현목록
- [x] 로그인 시, 로그아웃과 마이페이지가 보이도록 수정하기

**Comment by hann3** [comment]
원인을 찾았습니다 😅 크게 두 가지였는데,
1. 기존에 추가한 데이터를 찾지 못해 새롭게 추가하는 점(비동기라 시점 문제가 아닐까 합니다)
2. redux-persist를 통해 데이터를 저장하고 있지만 해당 저장소를 활용하고 있지 않더라고요  

수정해서 금방 올리겠습니다
