### ISSUE TITLE
예약페이지로 데이터 넘기는 방법

### ISSUE THREAD

**Issue by ktmihs** [thenolja/desktop#161]
## 설명
여러분의 도움 원해요...
호텔 객실을 선택한 후, 예약페이지로 넘어갈 때 어떤 방법으로 하는게 가장 효율적일지 도움 받습니다😭

**1. useContext 사용**
   - 상하관계가 아니라 다른 컴포넌트로 넘어가는 것이기 때문에 래핑이 애매한 느낌
   - 현재 redux를 사용 중이니 context를 사용할 바엔 redux를 사용하는 것도 나쁘지 않을 것 같음
  
**2. redux 사용**
   - 현재 사용 중인 redux에 reducer만 추가해서 정보 넘기기
   - 전역으로 관리할 필요가 없는 데이터를 굳이 redux에 넣는게 맞는지 모르겠음

**3. 호텔 id랑 객실 이름만 넘겨서 이동한 페이지에서 정보를 조회해서 데이터를 얻는다**
   - 서버에 한 번 더 요청해야함
   - 요청을 또 하는 것이 비효율적이라고 생각됨
  
**4. 쿼리로 전부 넘긴다**
   - 생각보다 넘겨야 할 데이터가 많아 굉장히 길어짐
   - 가장 단순한 방법인 것 같긴함
  
**5. 스토리지에 저장해서 받기**
   - 검색하다 찾게 된 방법

### 여러분의 선택은 ? 🤔

**Comment by sians5544** [comment]
저는 2번으로 가는게 좋을거 같습니다.... 이유는 같은 생각이라 생략...

**Comment by hann3** [comment]
(2) 선택한 호텔 정보가 전역에서 사용하는 게 아니라 Redux는 애매한 것 같고,  
(3) Hotels API에 한번 더 요청을 하는 것도 비효율적이라 생각됩니다... 
(4)나 스토리지를 활용한 (5)가 괜찮은 방법이라 생각되네요. 해당 정보는 개인 정보처럼 민감한 정보가 아니니까요

**Comment by parksaneon** [comment]
storage 에 넣는다면 sesstionstorage에 넣어도 될 꺼 같아요 
브라우저 닫은 후에 저장할 필요는 없는 거 같으니깐

**Comment by ktmihs** [comment]
@parksaneon @hann3 @sians5544 

모두의 의견 감사합니다
참고해서 잘 추가해 보겠읍니다요...🥰

**Comment by ktmihs** [comment]
모두의 의견덕분에 원만히 해결했습니다
감사합니당🙇‍♀️🥰
