### ISSUE TITLE
Header, Footer 공통영역 메모이제이션 

### ISSUE THREAD

**Issue by hann3** [thenolja/desktop#162]
## 설명
Header, Footer 공통 영역 메모이제이션
Header의 경우 id가 달라지는 경우를(로그인 -> 로그아웃 시 null) 제외하면 재렌더될 필요가 없고
Footer의 경우 늘 일정하므로 메모이제이션을 이용하는 것이 효율적 

## 구현 목록
- [x] useMemo를 사용하여 Header, Footer에 적용

**Comment by hann3** [comment]
![image](https://user-images.githubusercontent.com/48747805/160563290-bca2a0d2-4d89-4bb7-9f09-6439b7db97f0.png)

공통영역 useMemo를 사용했더니 성능에서 4점이 올랐네요 🥰

**Comment by ktmihs** [comment]
허걱... 혹시 당신은 초천재.... ?!??!
이상해씨처럼 푸릇푸릇한게 꽤나 멋져요🐸🐸
100점 너무 멋져요🤩
