### ISSUE TITLE
헤더, 푸터가 리렌더링되는 현상 

### ISSUE THREAD

**Issue by hann3** [thenolja/desktop#219]
## 설명
이번주 스프린트 목표 중 하나가 헤더, 푸터가 리렌더링되는 걸 수정하는 문제였는데요. 
React의 profile로 확인해 본 결과 푸터의 경우, 렌더링되는 걸 확인하지 못했습니다. 혹시나 확인한 분이 있다면 제보해 주세요 .😅
그리고 헤더의 경우, 매번 페이지 이동이 일어날 때마다 useMemo를 사용했음에도 렌더링되는 모습을 확인했는데
원인은 이렇습니다.

![image](https://user-images.githubusercontent.com/48747805/163682510-94a149f4-2b63-481d-9423-663825700cc1.png)

Header가 렌더링된 이유를 살펴 보면 부모 컴포넌트가 렌더링되었기 때문에 재렌더링되었다고 나옵니다.

💡 내부에는 Link가 존재하는데요. 이들을 모두 메모한 뒤 확인해도 동일한 이유로(부모 컴포넌트) 재렌더링됩니다. 

![image](https://user-images.githubusercontent.com/48747805/163684966-e8dfd302-9688-41f3-aee5-de24cdc13a5b.png)
 

결론은 헤더에 있는 버튼들(장바구니, 마이페이지 등) 클릭할 때마다 location이 변경되어 Router, Header, Link 모두 리렌더링될 수 밖에 없는 구조라고 생각됩니다. Header의 경우 path를 확인하기 위해 useLocation을 사용하고 있으니까요. 

그래서 이 부분은 건드리기 어려울 것 같습니다.

혹시 잘못됐거나 다른 의견이 있으시다면 부탁드립니다! 😄

**Comment by ktmihs** [comment]
헤더의 리렌더링이 발생하는 것은 불가피해 보입니다.😅
만약 Header에 useMemo를 사용하지 않는 것과 같은 결과를 야기한다면 useMemo를 사용하지 않아도 무방해보입니다!
아직 갈 길이 멀고도 험하네요...😂
수고하셨습니당!

**Comment by sians5544** [comment]
한나님 덕분에 또 알아갑니다.... 정리하여 올려주셔서 감사해요 원인 파악하시느라 수고 많으셨습니다. 👏👏👏
