### ISSUE TITLE
components, containers 등 디렉토리 구분

### ISSUE THREAD

**Issue by ktmihs** [thenolja/desktop#29]
## 설명
- components가 아닌, containers 내부에 Header, Main, Footer가 들어가는 것이 맞는 것 같기도?🤔
history 유지한 채, components, containers 디렉토리 구분 가능하신 분의 도움 받습니다🐰

- 그 외, 세분화할 수 있다면 추가 부탁드립니다 !

**Comment by hann3** [comment]
현재 컴포넌트 폴더에 모든 파일이 들어가 있는데 Pages 폴더를 별도로 생성하여 작업 중입니다. Header, Main, Footer의 경우 Containers 내부로 들어가는 것이 좋겠지요~ 일단 각자 작업한 뒤 회의 때 얘기해 봐도 좋을 것 같습니다

**Comment by ktmihs** [comment]
@hann3  헉 혹시 제가 오전에 pages 폴더 만든 후, 푸시했는데 풀 받으셨나요...? 충돌날 수도 있을 것 같아서 확인 부탁드립니다 !

**Comment by hann3** [comment]
@ktmihs 올리기 전에 풀을 받았네요^^; 그 부분은 따로 확인하겠습니다!

**Comment by ktmihs** [comment]
@hann3  네 감사합니다😘~💋
