### ISSUE TITLE
상세페이지-편의시설

### ISSUE THREAD

**Issue by sians5544** [thenolja/desktop#64]
## 설명
상세페이지의 편의시설

## 구현목록
- [x] 숙박 시설 위치 고객의 평가 마크업 및 스타일 작업 
- [x] 숙박 시설 특징 마크업 및 스타일 작업
- [x] 호텔의 편의시설 API 데이터 불러오는 작업

**Comment by ulgoon** [comment]
편의시설의 정의가 뭐죠?
