### ISSUE TITLE
리뷰 이미지 추가 관련 이슈 

### ISSUE THREAD

**Issue by hann3** [thenolja/desktop#94]
## 설명
Hotels API에서는 리뷰에 이미지를 제공하지 않지만 더놀자에서는 리뷰에 사진 첨부 기능을 제공합니다.
이미지 추가 기능을 제외할지, 아니면 API에는 없지만 저희가 따로 이미지를 추가할지  의견 공유 부탁드려요!

## 구현목록
- [ ] 리뷰 이미지 관련 기능 수정

**Comment by hann3** [comment]
저는 따로 이미지를 추가한다면, 저희가 제작한 리뷰 목데이터에는 이미지가 있으니 그걸 보여주고, 이미지가 없는 hotels api 데이터의 경우 기본 이미지로 호텔, 객실 이미지를 보여 주면 좋을 것 같습니다. 쇼핑몰에서 상품 사진을 보여주듯이요

**Comment by sians5544** [comment]
리뷰 페이지에서 이미지를 보여준다면 지금 리뷰페이지 디자인을  손 봐야할거같아서 시간이 걸릴거 같습니다 !!

**Comment by hann3** [comment]
디자인 외에 다른 문제는 없나요? 문제가 없다면 우선순위를 나중으로 두고, 다른 작업들이 완료된 뒤 손보면 될듯한데... 
내 리뷰 남기기쪽도 이미지 첨부 기능을 제외하면 ui가 너무 비어 보이진 않을까 걱정이네요 🤔

**Comment by hann3** [comment]
![image](https://user-images.githubusercontent.com/48747805/159612203-0e627810-f7fc-4ba1-9d8d-4d39989115dd.png)
![image](https://user-images.githubusercontent.com/48747805/159612254-b1d5052f-f625-4962-be96-eb2d65c4194b.png)


이미지 제외하기 전후입니다 다른 분들도 보시고 천천히라도 의견 부탁드려요 
+
천천히는.. 안되겠네요 이틀 뒤가 중간 발표입니다 ^^;

**Comment by ktmihs** [comment]
애초에 호텔스 데이터에 이미지가 있는 것으로 착각하고 넣기로 했으니까 호텔스 데이터를 사용한 한, 없는게 더 자연스러워 보이긴 하는데요^^; 일단 나머지 구현 완료 후, 시간적 여유가 된다면 다시 고려해보는 건 어떨까요?

**Comment by hann3** [comment]
호텔스 데이터를 사용한다고 해서 호텔스의 리뷰를 무조건 따라갈 필요는 없으니까요~  일단은 이름부터 더놀자이기도 하고... 😅 (야놀자에는 포토리뷰가.. 존재하죠?) 다른 기능이 구현된 뒤 상의해보자에는 동의합니다
